using System;
using BSIT3L_Movies.Models;
using Microsoft.AspNetCore.Mvc;
using static System.Net.WebRequestMethods;

namespace BSIT3L_Movies.Controllers
{
	public class MoviesController : Controller
    {
        private List<MovieViewModel> _movies;
        public MoviesController()
		{
            // Sample movie data
            _movies = new List<MovieViewModel>
            {
            new MovieViewModel { Id = 1, Name = "Dark Knight", Rating = "7", ReleaseYear = 2008, Genre = "Action/ Thriller",Description =" With the help of allies Lt. Jim Gordon (Gary Oldman) and DA Harvey Dent (Aaron Eckhart), Batman (Christian Bale) has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker (Heath Ledger) suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.",ImageSource = "/Img/dark.jpg", YTurl = "https://www.youtube.com/watch?v=LDG9bisJEaI",movieURL = "https://myflixerz.to/movie/the-dark-knight-19752"},
            new MovieViewModel {  Id = 2, Name = "Inception", Rating = "4", ReleaseYear = 2010, Genre = "Science Fiction/Thriller", Description = "Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone's mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb's every move." , ImageSource = "/Img/inception.jpg",YTurl = "https://youtu.be/JE9z-gy4De4",movieURL= " https://myflixerz.to/movie/inception-19764"},
            new MovieViewModel { Id = 3, Name = "The Shawshank Redemption", Rating = "5", ReleaseYear = 1994, Genre = "Drama", Description = " Andy Dufresne (Tim Robbins) is sentenced to two consecutive life terms in prison for the murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn't commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 years.", ImageSource = "/Img/redemption.jpg ", YTurl="https://youtu.be/NmzuHjWmXOc" , movieURL = "https://myflixerz.to/movie/the-shawshank-redemption-19679"},
            new MovieViewModel { Id = 4, Name = "The Lord of the Rings: The Return of the King", Rating = "8", ReleaseYear = 2003, Genre = "Fantasy/Adventure" , Description = "The culmination of nearly 10 years' work and conclusion to Peter Jackson's epic trilogy based on the timeless J.R.R. Tolkien classic, \"The Lord of the Rings: The Return of the King\" presents the final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the `one ring', while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.", ImageSource = "/Img/lordoftherings.jpg",YTurl= "https://youtu.be/y2rYRu8UW8M", movieURL = " https://myflixerz.to/movie/the-lord-of-the-rings-the-return-of-the-king-19681"},
            new MovieViewModel { Id = 5, Name = "Forrest Gump", Rating = "7", ReleaseYear = 1994, Genre = "Romance/ Drama" , Description = "Slow-witted Forrest Gump (Tom Hanks) has never thought of himself as disadvantaged, and thanks to his supportive mother (Sally Field), he leads anything but a restricted life. Whether dominating on the gridiron as a college football star, fighting in Vietnam or captaining a shrimp boat, Forrest inspires people with his childlike optimism. But one person Forrest cares about most may be the most difficult to save -- his childhood love, the sweet but troubled Jenny (Robin Wright) ", ImageSource = "/Img/forrestgrump.jpg", YTurl = "https://youtu.be/bLvqoHBptjg", movieURL ="https://myflixerz.to/movie/forrest-gump-19710"},
            new MovieViewModel { Id = 6, Name = "A Quiet Place II ", Rating = "9", ReleaseYear = 2020, Genre = "Sci Fi/Thriller",Description = "Following the deadly events at home, the Abbott family must now face the terrors of the outside world as they continue their fight for survival in silence. Forced to venture into the unknown, they quickly realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.", ImageSource = "/Img/Quietplace.jpg ",YTurl= " https://youtu.be/BpdDN9d9Jio", movieURL = " https://myflixerz.to/movie/a-quiet-place-part-ii-66697"},
            new MovieViewModel { Id = 7, Name = "Logan Lucky ", Rating = "4", ReleaseYear = 2017, Genre = "Crime/Comedy" , Description = "West Virginia family man Jimmy Logan teams up with his one-armed brother Clyde and sister Mellie to steal money from the Charlotte Motor Speedway in North Carolina. Jimmy also recruits demolition expert Joe Bang to help them break into the track's underground system. Complications arise when a mix-up forces the crew to pull off the heist during a popular NASCAR race, while also trying to dodge a relentless FBI agent.", ImageSource =" /Img/logan.jpg", YTurl ="https://youtu.be/aPzvKH8AVf0",movieURL = " https://myflixerz.to/movie/logan-lucky-18870"},
            new MovieViewModel { Id = 8, Name = "West Side Story", Rating = "9", ReleaseYear = 2021, Genre = "Musical/Romance " , Description = "A musical in which a modern day Romeo and Juliet are involved in New York street gangs. On the harsh streets of the upper west side, two gangs battle for control of the turf. The situation becomes complicated when a gang members falls in love with a rival's sister ", ImageSource = "/Img/westside.jpg", YTurl = " https://youtu.be/A5GJLwWiYSg",movieURL= "https://myflixerz.to/movie/west-side-story-17545"},
            new MovieViewModel { Id = 9, Name = "An Education", Rating = "7", ReleaseYear = 2009, Genre = "Drama/Romance", Description= " Despite her sheltered upbringing, Jenny (Carey Mulligan) is a teen with a bright future; she's smart, pretty, and has aspirations of attending Oxford University. When David (Peter Sarsgaard), a charming but much older suitor, motors into her life in a shiny automobile, Jenny gets a taste of adult life that she won't soon forget." , ImageSource =" /Img/educ.jpg", YTurl = " https://youtu.be/eRbp-dd1QvM", movieURL = " https://myflixerz.to/movie/an-education-13039"},
            new MovieViewModel { Id = 10, Name = "It's Kind Of A Funny Story", Rating = "6", ReleaseYear = 2010, Genre = "Drama/ Romance", Description = "Stressed by adolescence, 16-year-old Craig Gilner (Keir Gilchrist) checks himself into a mental-health clinic. Unfortunately, the youth wing is closed, so he must spend his mandated five-day stay with adults. One of them, Bobby (Zach Galifianakis), quickly becomes his mentor -- and protege, while Craig finds himself drawn to a fellow teen, Noelle (Emma Roberts), who just may be the cure he needs to forget an unrequited crush. ", ImageSource = "/Img/funnystory.jpg", YTurl = " https://youtu.be/0dSk92CbuFE", movieURL = " https://myflixerz.to/movie/its-kind-of-a-funny-story-13416"},
            new MovieViewModel { Id = 11, Name = "Pirates of the Caribbean: Dead Men Tell No Tales ", Rating = "9", ReleaseYear = 2017, Genre = "Action/ Thriller" , Description = " The story follows Captain Jack Sparrow (Depp) searches for the Trident of Poseidon to defeat Armando Salazar (Bardem), who is determined to kill every pirate at sea and take revenge on Sparrow for imprisoning him and his crew of ghosts in the Devil's Triangle.", ImageSource =" /Img/pirates.jpg", YTurl = " https://youtu.be/Hgeu5rhoxxY", movieURL = " https://myflixerz.to/movie/pirates-of-the-caribbean-dead-men-tell-no-tales-19572"},
            new MovieViewModel { Id = 12, Name = "Furious 7", Rating = "9", ReleaseYear = 2015, Genre = "Action/ Thriller", Description = " After defeating international terrorist Owen Shaw, Dominic Toretto (Vin Diesel), Brian O'Conner (Paul Walker) and the rest of the crew have separated to return to more normal lives. However, Deckard Shaw (Jason Statham), Owen's older brother, is thirsty for revenge. A slick government agent offers to help Dom and company take care of Shaw in exchange for their help in rescuing a kidnapped computer hacker who has developed a powerful surveillance program.", ImageSource= " /Img/F7.jpg", YTurl = " https://youtu.be/Skpu5HaVkOc" , movieURL = " https://myflixerz.to/movie/furious-7-19588"},
            new MovieViewModel { Id = 13, Name = "Where The Crawdads Sing ", Rating = "7", ReleaseYear = 2020, Genre = "Drama/ Thriller", Description = " Abandoned as a girl, Kya raised herself in the dangerous marshlands of North Carolina. For years, rumors of the marsh girl haunted Barkley Cove, isolating the sharp and resilient Kya from her community. Drawn to two young men from town, she opens herself to a new and startling world. However, when one of them is found dead, Kya immediately becomes the main suspect. As the case unfolds, the verdict as to what happened becomes increasingly unclear, threatening to reveal many secrets" , ImageSource = " /Img/crawdadsing.jpg",YTurl= " https://youtu.be/PY3808Iq0Tg" , movieURL = " https://myflixerz.to/movie/where-the-crawdads-sing-85005"},
            new MovieViewModel { Id = 14, Name = "A Better Life", Rating = "8", ReleaseYear = 2015, Genre = "Drama/ Romance" ,Description = " Carlos Galindo (Demián Bichir), a Mexican illegal immigrant and veteran Los Angeles day laborer, has trouble connecting with his son, Luis (José Julián), whose gang-affiliated girlfriend is tempting him to ignore his father's example of clean living. Carlos buys a truck to begin working as a self-employed man and earn more money, but when it is stolen, his hopes for a more affluent life are dashed. Unable to turn to the police for help, father and son embark on a quest to find the vehicle. ", ImageSource = " /Img/betterlife.jpg", YTurl = " https://youtu.be/mwIzW7yk3ZI", movieURL = " https://myflixerz.to/movie/a-better-life-8759"},
            new MovieViewModel { Id = 15, Name = "Dungeons & Dragons: Honor Among Thieves", Rating = "5", ReleaseYear = 2023, Genre = "Action/ Thriller", Description = " A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a long lost relic, but their charming adventure goes dangerously awry when they run afoul of the wrong people.", ImageSource = " /Img/dugeons.jpg", YTurl = " https://youtu.be/IiMinixSXII", movieURL = " https://myflixerz.to/movie/dungeons-dragons-honor-among-thieves-94312" },
            };
        }
        public ActionResult Random()
        {
            var movie = new MovieViewModel() { Name = "Avatar", Rating = "5" };
            return View(movie);
        }
        public ActionResult GetMovie(int id)
        {
            var movie = _movies.Find(m => m.Id == id);
            if (movie == null)
                return NotFound();
            return View(movie);

        }

    }
}

